name: tus_client_file_store
description: A file based storage for tus_client that you can use to save the state resumable uploads even after restarting device.
version: 0.0.2
homepage: https://github.com/jjmutumi/tus_client_file_store

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.7.0
  tus_client: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
